### ISSUE TITLE
Generation via CMVFS/LCG Source

### ISSUE THREAD

**Issue by j-s-ashley** [A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY#30]
MadGraph, as sourced from LCG on LXPlus, is not set up to allow for showering via Pythia. 

![image](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/assets/143551418/ecabc26d-db3f-4ddb-836f-eae646f7ace0)

The process I used to produce this result:
1. Connect to LXPlus via SSH using Termius.
2. Ensure Kerberos tickets are valid.
`klist` and, if necessary, `kinit`
4. Authenticate grid proxy with CMS VOMS.
`voms-proxy-init --rfc --voms cms -valid 192:00`
5. Source the view.
`source /cvmfs/sft.cern.ch/lcg/views/LCG_105/x86_64-el9-gcc13-opt/setup.sh` (for example)
6. Run MadGraph.
`mg5_aMC`
7. Manual input of commands contained in [this proc card](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/blob/af419da5604b5350ea57eb914b9e8003cebccd55/generate_events/small_proc_card.dat) up to `shower=Pythia8`.
8. Glare at error.

When I try to get MadGraph to install Pythia for showering (by entering the command `install pythia8` after step 6), it yells at me about the file system being read-only.

![image](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/assets/143551418/45d871b6-f02e-4ae9-93eb-28630c1d6b9f)

I have tried the following releases: 105, 105a, 104, 104swan

**Comment by j-s-ashley** [comment]
Closed as insurmountable without admin intervention. We'll be using MadGraph and Pythia separately.

**Comment by trholmes** [comment]
Can you make a ticket for the LCG folks before closing?

**Comment by j-s-ashley** [comment]
Ah, that would be smart! I'll get a ticket drafted and include that info in this issue as well. Thanks!

**Comment by j-s-ashley** [comment]
JIRA issue created: [https://its.cern.ch/jira/browse/SPI-2537](https://its.cern.ch/jira/browse/SPI-2537)

I'll update with any responses!

**Comment by j-s-ashley** [comment]
The Plot Intensifies...

Pythia, as sourced via LCG, has a similar problem.

Basic functionality is intact, but the HepMC libraries (for both 2e and 3e) are not linked in the Pythia configuration files. 
![image](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/assets/143551418/8a708a2f-d88c-439f-ab2d-1abd31932d00)

This means that, although we *can* shower with Pythia, since (thankfully) the LHE-input reading functionality is built into Pythia's own code, we cannot output in HepMC format.

**Comment by j-s-ashley** [comment]
Attempts to set LD_LIBRARY_PATH to include the HepMC libraries have not been productive. 

I tacked the path to the HepMC library onto the end of the existing string for LD_LIBRARY_PATH, then tried running a basic HepMC output Pythia example file and was met with a familiar wall of "undefined reference" errors. 🍻

**Comment by j-s-ashley** [comment]
> the HepMC libraries (for both 2e and 3e) are not linked in the Pythia configuration files

This is true in **most** LCG views, but not all. After being shown a list of Pythia packages with the HEPMC2_USE flag set to true, I was able to track down a handful of views that used those packages. 

The most up-to-date view that contains working installations of MadGraph and HepMC-enabled Pythia is located on LXPlus here: 
/cvmfs/sft.cern.ch/lcg/views/LCG_102b_ATLAS_6/x86_64-centos9-gcc11-opt/setup.sh

I'll be updating the [generate_events README](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/blob/secondary/generate_events/README.md) to include the full process of setting up the LCG view to use both generators.

Effectively, this issue has been circumnavigated, though the core problem (none of the LCG stacks allow MadGraph to shower with Pythia seamlessly) still exists.
