### ISSUE TITLE
Acceptance plot/table

### ISSUE THREAD

**Issue by A-A-Abdelhamid** [A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY#6]
Hi @trholmes,

I feel dumb asking this but I am not sure I understand the smuon acceptance table/graph here:

https://www.hepdata.net/record/ins1831504?version=2&table=Smuon%20acceptance

![Screenshot 2023-08-10 at 2 10 31 PM](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/assets/130788379/a48aefce-b296-4ff1-bfdf-efcc3d10f430)
![Screenshot 2023-08-10 at 2 26 01 PM](https://github.com/A-A-Abdelhamid/LLP_Sleptons_RPV_SUSY/assets/130788379/abfdb719-7ef0-46ec-b4db-50d927a8631b)

![](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/SUSY-2018-14/figaux_14a.png)

They only sample 4 points in lifetime (log of -1.5, -0.5, 0.5, and 1.5 ns) and only one point within each approximately 100 GeV mass range (for example they go from 325GeV directly to 425GeV then to 525 GeV)

There is nothing special about the those lifetimes except they make the log graph looks nice. 10^-1.5 gives a lifetime of 0.0316 ns, and 10^1.5 is 31.62 ns. 

The search is done over 0.01 ns to 100 ns, which corresponds to log lifetimes of -2 to 2, so now I think that these few points are somehow "representative" of the entire samples, i.e. I could "interpolate" the rest of acceptance data points from it, but this is not how things usually work. I opened the csv and Json files and they have the same data points as the table above. Are these the only lifetimes and masses they tested for acceptance?

Maybe my brain is still frying from the quals :)

Thanks!

**Comment by trholmes** [comment]
Hi Alaa,

You understand things correctly. 

Interpolations were done between the 100 GeV-spaced mass points (btw they are at 100, 200, 300 GeV etc, not 125, 225, etc). Between the lifetime points we did something a bit more complicated to interpolate, which involved reweighting samples to different lifetimes. Don't worry about that just yet -- we can get to it later.

**Comment by A-A-Abdelhamid** [comment]
Thanks a lot for the clarification! This makes sense now.
